sudo: required

before_install:
  - sudo apt-get install cmake

os:
  - linux
  
language: 
  - cpp

compiler:
  - gcc
  - clang
  
matrix:
  include:
    - os: linux
      compiler: clang
      env: ASAN=ON
    - os: linux
      compiler: clang
      env: ANALYZE=ON
    - os: linux
      compiler: clang
      env: UBSAN=ON
    - os: linux
      compiler: gcc
    - os: linux
      compiler: gcc
      env: ANALYZE=ON

script: 
  - . ./.travis.sh
